name: building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: load_repository
        uses: actions/checkout@v4
      - run: git clone https://github.com/google/googletest banking/third-party/gtest
      - name: Build
        run: cmake -H. -B build && cmake --build build

      - name: Test
        run: cmake --build build && cmake --build build
